apiVersion: v2
appVersion: 0.20.0
description: Apache Druid is a high performance real-time analytics database.
name: druid
version: 0.3.13
home: https://druid.apache.org/
icon: https://druid.apache.org/img/favicon.png
sources:
  - https://github.com/SambaTV/charts/tree/main/charts/druid
keywords:
  - olap
  - database
  - analytics

dependencies:
- name: zookeeper
  version: 7.6.2
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: mysql
  version: 8.2.7
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: postgresql
  version: 10.2.3
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: prometheus-druid-exporter
  alias: prometheusDruidExporter
  version: 0.9.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheusDruidExporter.enabled
