{{- if .Values.historical.ingress.enabled -}}
{{- $fullName := include "druid.historical.fullname" . -}}
{{- $ingressPath := .Values.historical.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.historical.name }}
  {{- with .Values.historical.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.historical.ingress.ingressClassName }}
  ingressClassName: {{ .Values.historical.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.historical.ingress.tls }}
  tls:
    {{- range .Values.historical.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.historical.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
  {{- end }}
