{{- if .Values.historical.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.historical.name }}
  name: {{ template "druid.historical.fullname" . }}
spec:
{{- if .Values.historical.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.historical.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.historical.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.historical.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "druid.selectorLabels" . | nindent 6 }}
      component: {{ .Values.historical.name }}
{{- end }}