{{- if .Values.historical.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.historical.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.historical.name }}
spec:
  type: {{ .Values.historical.serviceType }}
  ports:
    - port: {{ .Values.historical.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "druid.selectorLabels" . | nindent 4 }}
    component: {{ .Values.historical.name }}
{{- end }}