{{- if .Values.coordinator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "druid.coordinator.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.coordinator.name }}
spec:
  replicas: {{ .Values.coordinator.replicaCount }}
  selector:
    matchLabels:
      {{- include "druid.selectorLabels" . | nindent 6 }}
      component: {{ .Values.coordinator.name }}
  template:
    metadata:
      {{- with .Values.coordinator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "druid.selectorLabels" . | nindent 8 }}
        component: {{ .Values.coordinator.name }}
    spec:
      serviceAccountName: {{ include "druid.serviceAccountName" . }}
{{- if .Values.coordinator.securityContext }}
      securityContext:
{{ toYaml .Values.coordinator.securityContext | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "coordinator" ]
          env:
          {{- range $key, $val := .Values.coordinator.config }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
{{- if .Values.coordinator.extraEnv }}
{{- toYaml .Values.coordinator.extraEnv| nindent 10 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "druid.name" . }}
{{ if .Values.extraConfig.envFrom }}
{{ toYaml .Values.extraConfig.envFrom | indent 12 }}
{{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.coordinator.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.coordinator.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.coordinator.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.coordinator.livenessProbe.periodSeconds }}
            httpGet:
              path: /status/health
              port: {{ .Values.coordinator.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.coordinator.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.coordinator.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.coordinator.readinessProbe.periodSeconds }}
            httpGet:
              path: /status/health
              port: {{ .Values.coordinator.port }}
          resources:
{{ toYaml .Values.coordinator.resources | indent 12 }}
          volumeMounts:
            - mountPath: /opt/druid/var
              name: data
  {{- if .Values.gCloudStorage.enabled }}
            - name: google-cloud-key
              mountPath: /var/secrets/google
  {{- end }}
  {{- if .Values.coordinator.extraVolumeMounts }}
  {{- toYaml .Values.coordinator.extraVolumeMounts | nindent 12 }}
  {{- end }}
      volumes:
        - name: data
          emptyDir: {}
  {{- if .Values.gCloudStorage.enabled }}
      - name: google-cloud-key
        secret:
          secretName: {{ .Values.gCloudStorage.secretName }}
  {{- end }}
  {{- if .Values.coordinator.extraVolumes }}
  {{- toYaml .Values.coordinator.extraVolumes | nindent 8 }}
  {{- end }}
    {{- with .Values.coordinator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.coordinator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.coordinator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}