{{- if .Values.middleManager.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.middleManager.name }}
  name: {{ template "druid.middleManager.fullname" . }}
spec:
  serviceName: {{ template "druid.middleManager.fullname" . }}
  replicas: {{ .Values.middleManager.replicaCount }}
  selector:
    matchLabels:
      {{- include "druid.selectorLabels" . | nindent 6 }}
      component: {{ .Values.middleManager.name }}
  template:
    metadata:
      {{- with .Values.middleManager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "druid.selectorLabels" . | nindent 8 }}
        component: {{ .Values.middleManager.name }}
    spec:
      serviceAccountName: {{ include "druid.serviceAccountName" . }}
      {{- if or .Values.middleManager.antiAffinity .Values.middleManager.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.middleManager.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.middleManager.name }}"
      {{- else if eq .Values.middleManager.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.middleManager.name }}"
      {{- end }}
      {{- with .Values.middleManager.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.middleManager.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.middleManager.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.middleManager.securityContext }}
      securityContext:
{{ toYaml .Values.middleManager.securityContext | indent 8 }}
{{- end }}
{{- if .Values.middleManager.tolerations }}
      tolerations:
{{ toYaml .Values.middleManager.tolerations | indent 8 }}
{{- end }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}
      containers:
      - name: druid
        args: [ "middleManager" ]
        env:
        {{- range $key, $val := .Values.middleManager.config }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        envFrom:
          - configMapRef:
              name: {{ template "druid.name" . }}
{{ if .Values.extraConfig.envFrom }}
{{ toYaml .Values.extraConfig.envFrom | indent 12 }}
{{ end }}
        resources:
{{ toYaml .Values.middleManager.resources | indent 12 }}
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.middleManager.port }}
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.middleManager.port }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.middleManager.port }}
          name: http
        volumeMounts:
        - mountPath: /opt/druid/var/
          name: data
  {{- if .Values.gCloudStorage.enabled }}
        - name: google-cloud-key
          mountPath: /var/secrets/google
  {{- end }}
      volumes:
  {{- if not .Values.middleManager.persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- end }}
  {{- if .Values.gCloudStorage.enabled }}
      - name: google-cloud-key
        secret:
          secretName: {{ .Values.gCloudStorage.secretName }}
  {{- end }}
  updateStrategy:
    type: {{ .Values.middleManager.updateStrategy.type }}
  {{- if .Values.middleManager.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .Values.middleManager.persistence.accessMode | quote }}
    {{- if .Values.middleManager.persistence.storageClass }}
    {{- if (eq "-" .Values.middleManager.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.middleManager.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.middleManager.persistence.size }}"
  {{- end }}
{{- end }}