{{- if .Values.broker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "druid.broker.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.broker.name }}
spec:
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      {{- include "druid.selectorLabels" . | nindent 6 }}
      component: {{ .Values.broker.name }}
  template:
    metadata:
      {{- with .Values.broker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "druid.selectorLabels" . | nindent 8 }}
        component: {{ .Values.broker.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "broker" ]
          env:
          {{- range $key, $val := .Values.broker.config }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
          envFrom:
            - configMapRef:
                name: {{ template "druid.name" . }}
          ports:
            - name: http
              containerPort: {{ .Values.broker.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /status/health
              port: {{ .Values.broker.port }}
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /status/health
              port: {{ .Values.broker.port }}
          resources:
{{ toYaml .Values.broker.resources | indent 12 }}
    {{- with .Values.broker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.broker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.broker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}