{{- if .Values.overlord.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "druid.overlord.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
    component: {{ .Values.overlord.name }}
spec:
  replicas: {{ .Values.overlord.replicaCount }}
  selector:
    matchLabels:
      {{- include "druid.selectorLabels" . | nindent 6 }}
      component: {{ .Values.overlord.name }}
  template:
    metadata:
      {{- with .Values.overlord.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "druid.selectorLabels" . | nindent 8 }}
        component: {{ .Values.overlord.name }}
    spec:
      serviceAccountName: {{ include "druid.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "overlord" ]
          env:
          {{- range $key, $val := .Values.overlord.config }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
          envFrom:
            - configMapRef:
                name: {{ template "druid.name" . }}
{{ toYaml .Values.extraConfig.envFrom | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.overlord.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /status/health
              port: {{ .Values.overlord.port }}
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /status/health
              port: {{ .Values.overlord.port }}
          resources:
{{ toYaml .Values.overlord.resources | indent 12 }}
          volumeMounts:
  {{- if .Values.gCloudStorage.enabled }}
            - name: google-cloud-key
              mountPath: /var/secrets/google
  {{- end }}
      volumes:
  {{- if .Values.gCloudStorage.enabled }}
      - name: google-cloud-key
        secret:
          secretName: {{ .Values.gCloudStorage.secretName }}
  {{- end }}
    {{- with .Values.overlord.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.overlord.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.overlord.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
